name: Dependency Submission (npm)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Submit npm Dependencies
        uses: actions/dependency-review-action@v4.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
